In [1]:
import streamlit as st
import pandas as pd
from tensorflow.keras.models import load_model
import pickle

st.title("Passenger Survival Chance in the Titanic Journey")

pclass = st.slider('Enter the Passenger class for the user', 1, 3)
sex = st.selectbox('Enter the Passenger Gender', ['male', 'female'])

2026-07-20 17:05:54.768 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.898
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]
2026-07-20 17:05:54.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.900 Session state does not function when running a script without `streamlit run`
2026-07-20 17:05:54.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:05:54.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [2]:
sibsp = st.slider('Enter the Passenger Sibling and Spouse',1 , 8)
parch = st.slider ('Enter the Passenger total number of Parents and Child', 0, 6)
fare = st.number_input('Enter the fare of the passenger')
embarked = st.selectbox('Enter the Passenger station from where they started the Journey',['Southampton', 'Chebourg', 'Queenstown'])

2026-07-20 17:06:00.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-20 17:06:00.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [3]:
data = pd.DataFrame([{'Pclass':pclass,
               'Sex':sex,
               'SibSp':sibsp,
               'Parch':parch,
               'Fare':fare,
               'Embarked':embarked}])

In [4]:
model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [5]:
with open('label_encoder.pkl', 'rb') as file:
    label = pickle.load(file)

In [6]:
with open('onehot_encoder.pkl', 'rb') as file:
    onehot = pickle.load(file)

In [16]:
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [19]:
data['Sex'] = label.transform(data['Sex'])

In [20]:
onehot.get_feature_names_out()

array(['Embarked_Chebourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype=object)

In [21]:
embarked = onehot.transform(data[['Embarked']])

KeyError: "None of [Index(['Embarked'], dtype='object')] are in the [columns]"

In [ ]:
embarked

array([[0., 0., 1.]])

In [22]:
embarked = pd.DataFrame(embarked, columns=onehot.get_feature_names_out())

In [12]:
embarked

   Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                0.0                  0.0                   1.0

In [13]:
data = pd.concat([data.drop(columns = ['Embarked']), embarked], axis = 1)

In [14]:
data

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1,male,1,0,0.0,0.0,0.0,1.0

In [17]:
data[['Pclass', 'SibSp', 'Parch', 'Fare']] = scaler.transform(data[['Pclass', 'SibSp', 'Parch', 'Fare']])

In [18]:
y = model.predict(data)

ValueError: could not convert string to float: 'male'